### ISSUE TITLE
eSpinn error in compilation

### ISSUE THREAD

**Issue by lonnietc** [hnqiu/eSpinn#1]
Hello,

I just came across your eSpinn work and am trying to get it to run on my Ubuntu 20.04 system.

I have been able to install and run the FlappyBird code from your Repo but seem to have a problem when compiling the eSpinn code.

```
eSpinn/build$ cmake ..
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.58") found components: serialization
-- Found PythonInterp: /usr/bin/python3.7 (found version "3.7.13")
CMake Error at /usr/lib/cmake/pybind11/FindPythonLibsNew.cmake:96 (message):
  Python config failure:

  Traceback (most recent call last):

    File "<string>", line 1, in <module>

  ImportError: cannot import name 'sysconfig' from 'distutils'
  (/usr/lib/python3.7/distutils/__init__.py)

Call Stack (most recent call first):
  /usr/lib/cmake/pybind11/pybind11Tools.cmake:16 (find_package)
  /usr/lib/cmake/pybind11/pybind11Config.cmake:100 (include)
  CMakeLists.txt:8 (find_package)


-- Configuring incomplete, errors occurred!

```

Any thoughts on how to fix this?

**Comment by hnqiu** [comment]
Hi,
Thanks for your interest in this work.

Yeah I am still updating the documentation and the necessary packages have not been documented yet.
To build this package, you will need Boost serialization (Boost should have already been available on Ubuntu) & pybind11.

To install pybind11, please refer to my post: https://hnqiu.github.io/2020/05/19/pybind11/
I will add this to README later.

Let me know if you have further issues.

hnqiu

**Comment by hnqiu** [comment]
Updated. Please pull the latest.

If your pybind11 is installed via conda, build this package by specifying the python path to the conda instance, e.g.
```
cmake -DPYTHON_EXECUTABLE="$HOME/anaconda3/bin/python" ..
```
