### ISSUE TITLE
eSpinn relation to NEAT-SNN?

### ISSUE THREAD

**Issue by lonnietc** [hnqiu/eSpinn#3]
Hello,

I have been reading some of your papers:

https://arxiv.org/pdf/2002.09854.pdf  (2020)
and
https://arxiv.org/pdf/1903.01180.pdf (2019)

for which eSpinn "Evolving Spiking Neural Networks" is mentioned in the 2020 paper while NEAT "NeuroEvolution of Augmenting Topology" is mentioned more in the 2019 and previous papers.

In looking over these papers, it seems that the only real difference is the addition of a "bias neuron" in eSpinn that is not present in the NEAT-SNN network topology.

Can you please let me know if there are other differences as well since I am trying to get a better understanding as to what else has changed in the work for going from NEAT to eSpinn as it seems that eSpinn is an evolution and advance to the previous NEAT-SNN work?

Any information that you could provide would be greatly appreciated.

Also, if you have any more papers, thesis, or others specifically related to eSpinn then I would enjoy reading them as I am interested in combining this type of work into perhaps something like a SOINN "Self-Organizing Incremental Neural Network" clustering approach where concepts are learned and small eSpinn sub-networks are the action controllers for learnt algorithms.

Cheers and have a great day

**Comment by lonnietc** [comment]
Do you have any update on this one?

**Comment by hnqiu** [comment]
Hello,

The current eSpinn package uses a modified NEAT algorithm (i.e. MoNEAT), which is described in this paper https://ieeexplore.ieee.org/document/9308275

There was a plan for another paper in which I would introduce this package in more detail. However, as I have taken a role in industry, the progress has been very slow.
 
The following are some projects I found quite interesting, but I haven't followed the latest research on SNN for a while, so there must be some recent work I don't know.

https://github.com/fzenke/auryn
https://github.com/UCI-CARL/CARLsim4

Cheers

**Comment by hnqiu** [comment]
Initially the experiments were developed based on the NEAT package, which turned into the 2019 paper. Later, I tried to implement my own SNN package and customize the NEAT algorithm in this package, which finally became eSpinn.

**Comment by lonnietc** [comment]
Hello,

Thanks for your messages and links as they are really helpful.

Lately, I have been reviewing a lot of NEAT related papers as well as it seems that the UAV paper used MO-NEAT which is a modified NEAT approach. That led me to HyperNEAT which also seems to take into account the geometry of the system as well and I think that is a really interesting and worthy approach for NN systems to also consider the "environment" in which they are working and is more akin to biological systems, I think.

The thing that I like about your eSpinn is that it is a spiking NN and really think that holds a viable and useful avenue. 

What I am wondering though, as it is not clear to me so far, is if the HyperNEAT is also a spiking NN system. If not, then I wonder if that would be a go way to proceed as well so that it would be an evolution to eSpinn, perhaps.

Any thoghts?
