### ISSUE TITLE
Data file for tasks

### ISSUE THREAD

**Issue by lonnietc** [hnqiu/eSpinn#4]
Hello,

I have now been able to compile some of the other tasks.

Do you have a test data file for the "sim_approximation.sim" so that I can test it?

Also, do you have any more peer papers or ppt presentations on the eSpinn work that you, or others, have done?

Thanks again

**Comment by hnqiu** [comment]
`sim_approximation` is kinda outdated. I would recommend referring to `pole_balancing`, `sim_flappy` and `sim_ctrl`.
As you are able to build the pybind module, you can try running the flappy bird example. I have successfully run it with Python 3.9, so you don't need to install 3.7.

I've shared another paper in Issue #3. Currently the work has been more or less paused as I am working in the industry.

All the best
